version: "2"
linters:
  default: all
  disable:
    - exhaustruct
    - testpackage
    - wsl

  settings:
    ireturn:
      allow:
        - error
        - generic
    lll:
      line-length: 180
    paralleltest:
      ignore-missing: true
    revive:
      rules:
        - name: package-comments
          disabled: true
    varnamelen:
      ignore-decls:
        - i int

  exclusions:
    rules:
      - path: '(.+)_test\.go'
        linters:
          - goconst
      - path: '(.+)/examples_test\.go'
        linters:
          - depguard

formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
